// _id: is a string of 24 characters and every 2 characters are a byte

// 12 bytes
//     4 bytes: timestamp
//     3 bytes: machine identifier
//     2  bytes: process identifier
//     3 bytes: counter

// uniqueness of id is not guranteed 

// id is generated by mongo driver so we don't have to wait for MongoDB to genreate it. allows for scalablity 



// To gernate your own id
const mongoose = require('mongoose');
const id = new mongoose.Types.ObjectId();
console.log(id.getTimestamp());

const isValid = mongoose.Types.ObjectId.isValid('12345');
console.log(isValid)