// _id: is a string of 24 characters and every 2 characters are a byte

// 12 bytes
//     4 bytes: timestamp
//     3 bytes: machine identifier
//     2  bytes: process identifier
//     3 bytes: counter

// uniqueness of id is not guranteed 

// id is generated by mongo driver so we don't have to wait for MongoDB to genreate it. allows for scalablity 



// To gernate your own id
const mongoose = require('mongoose');
const id = new mongoose.Types.ObjectId();
console.log(id.getTimestamp());

const isValid = mongoose.Types.ObjectId.isValid('12345');
console.log(isValid)



// Error if id passed is not a valid objectId (1234) is passed to our Vidly app's rental api
// CastError: Cast to ObjectId failed for value "1234"  at path "_id" for model Customer
// path = chain of properties
// Mongo couldn't pass 1234 to objectId becasue it wasnt valid objectId